services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Add the correct path if Dockerfile is not in the same directory
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "./wait-for-it.sh db:5432 -- bunx prisma db push && bunx prisma generate && bun index.ts"

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: